<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CingZeoi.ChinesePinyinConverter" Version="1.0.0" />
    <PackageVersion Include="CodeWF.Log.Core" Version="12.0.3.1" />
    <PackageVersion Include="CodeWF.Tools" Version="1.3.13.2" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Hashids.net" Version="1.7.0" />
    <PackageVersion Include="Markdig" Version="1.2.0" />
    <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.6.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageVersion Include="QRCoder" Version="1.8.0" />
    <PackageVersion Include="TencentCloudSDK" Version="3.0.1439" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
