<Project>
  <PropertyGroup>
    <Version>1.1.1</Version>
    <AssemblyVersion>1.1.1.0</AssemblyVersion>
    <FileVersion>1.1.1.0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Authors>沙漠尽头的狼</Authors>
    <Company>dotnet9.com</Company>
    <Product>CodeWF</Product>
    <RepositoryUrl>https://github.com/dotnet9/CodeWF</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
