<Project>
  <PropertyGroup>
    <Version>2.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
    <InformationalVersion>$(Version)</InformationalVersion>
    <Authors>dotnet9</Authors>
    <Company>dotnet9.com</Company>
    <Product>CodeWF</Product>
    <RepositoryUrl>https://github.com/dotnet9/CodeWF</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
