<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CodeWF.Log.Core" />
		<PackageReference Include="Markdig" />
		<PackageReference Include="Hashids.net" />
		<PackageReference Include="CingZeoi.ChinesePinyinConverter" />
		<PackageReference Include="CodeWF.Tools" />
		<PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
		<PackageReference Include="QRCoder" />
		<PackageReference Include="TencentCloudSDK" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="WebApp.Tests" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="..\..\logo.svg" Link="logo.svg" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
		<Content Include="..\..\logo.png" Link="logo.png" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
		<Content Include="..\..\logo.ico" Link="logo.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>

</Project>
