CREATE TABLE CmUser (
    Id          character varying(50)  NOT NULL,
    CreateBy    character varying(50)  NOT NULL,
    CreateTime  timestamp without time zone NOT NULL,
    ModifyBy    character varying(50),
    ModifyTime  timestamp without time zone,
    Version     integer                NOT NULL,
    Extension   text,
    AppId       character varying(50),
    CompNo      character varying(50)  NOT NULL,
    UserName    character varying(50)  NOT NULL,
    Password    character varying(50)  NOT NULL,
    OpenId      character varying(50),
    UnionId     character varying(50),
    NickName    character varying(50),
    Sex         character varying(50),
    Country     character varying(50),
    Province    character varying(50),
    City        character varying(50),
    AvatarUrl   character varying(250),
    Metier      character varying(50),
    Status      character varying(50)  NOT NULL,
    Integral    integer,
    ContentQty  integer,
    ReplyQty    integer,
    PRIMARY KEY (Id)
);

CREATE TABLE CmCategory (
    Id          character varying(50)  NOT NULL,
    CreateBy    character varying(50)  NOT NULL,
    CreateTime  timestamp without time zone NOT NULL,
    ModifyBy    character varying(50),
    ModifyTime  timestamp without time zone,
    Version     integer                NOT NULL,
    Extension   text,
    AppId       character varying(50),
    CompNo      character varying(50)  NOT NULL,
    Type        character varying(50)  NOT NULL,
    ParentId    character varying(50)  NOT NULL,
    Code        character varying(50)  NOT NULL,
    Name        character varying(50)  NOT NULL,
    Icon        character varying(50),
    Sort        integer                NOT NULL,
    Enabled     character varying(50)  NOT NULL,
    Note        text,
    PRIMARY KEY (Id)
);

CREATE TABLE CmPost (
    Id          character varying(50)  NOT NULL,
    CreateBy    character varying(50)  NOT NULL,
    CreateTime  timestamp without time zone NOT NULL,
    ModifyBy    character varying(50),
    ModifyTime  timestamp without time zone,
    Version     integer                NOT NULL,
    Extension   text,
    AppId       character varying(50),
    CompNo      character varying(50)  NOT NULL,
    Type        character varying(50)  NOT NULL,
    UserId      character varying(50)  NOT NULL,
    CategoryId  character varying(50)  NULL,
    Title       character varying(250) NOT NULL,
    Content     text                   NOT NULL,
    Summary     character varying(500) NULL,
    Tags        character varying(200) NULL,
    Image       character varying(250) NULL,
    Files       character varying(250) NULL,
    Status      character varying(50)  NOT NULL,
    PublishTime timestamp without time zone,
    ViewQty     integer,
    LikeQty     integer,
    ReplyQty    integer,
    RankNo      integer,
    PRIMARY KEY (Id)
);

CREATE TABLE CmReply (
    Id          character varying(50)  NOT NULL,
    CreateBy    character varying(50)  NOT NULL,
    CreateTime  timestamp without time zone NOT NULL,
    ModifyBy    character varying(50),
    ModifyTime  timestamp without time zone,
    Version     integer                NOT NULL,
    Extension   text,
    AppId       character varying(50),
    CompNo      character varying(50)  NOT NULL,
    BizType     character varying(50)  NOT NULL,
    BizId       character varying(50)  NOT NULL,
    UserId      character varying(50)  NOT NULL,
    Content     text                   NOT NULL,
    ReplyTime   timestamp without time zone NOT NULL,
    LikeQty     integer,
    ReplyQty    integer,
    PRIMARY KEY (Id)
);

CREATE TABLE CmLog (
    Id          character varying(50)  NOT NULL,
    CreateBy    character varying(50)  NOT NULL,
    CreateTime  timestamp without time zone NOT NULL,
    ModifyBy    character varying(50),
    ModifyTime  timestamp without time zone,
    Version     integer                NOT NULL,
    Extension   text,
    AppId       character varying(50),
    CompNo      character varying(50)  NOT NULL,
    BizType     character varying(50)  NOT NULL,
    LogType     character varying(50)  NOT NULL,
    BizId       character varying(50)  NOT NULL,
    UserId      character varying(50)  NOT NULL,
    UserIP      character varying(50),
    PRIMARY KEY (Id)
);