CREATE TABLE [CmUser] (
    [Id]         varchar(50)      NOT NULL PRIMARY KEY,
    [CreateBy]   nvarchar(50)     NOT NULL,
    [CreateTime] datetime         NOT NULL,
    [ModifyBy]   nvarchar(50)     NULL,
    [ModifyTime] datetime         NULL,
    [Version]    int              NOT NULL,
    [Extension]  ntext            NULL,
    [AppId]      varchar(50)      NOT NULL,
    [CompNo]     varchar(50)      NOT NULL,
    [UserName]   nvarchar(50)     NOT NULL,
    [Password]   nvarchar(50)     NOT NULL,
    [OpenId]     varchar(50)      NULL,
    [UnionId]    varchar(50)      NULL,
    [NickName]   nvarchar(50)     NULL,
    [Sex]        nvarchar(50)     NULL,
    [Country]    nvarchar(50)     NULL,
    [Province]   nvarchar(50)     NULL,
    [City]       nvarchar(50)     NULL,
    [AvatarUrl]  nvarchar(250)    NULL,
    [Metier]     nvarchar(50)     NULL,
    [Status]     nvarchar(50)     NOT NULL,
    [Integral]   int              NULL,
    [ContentQty] int              NULL,
    [ReplyQty]   int              NULL
);

CREATE TABLE [CmCategory] (
    [Id]         varchar(50)      NOT NULL PRIMARY KEY,
    [CreateBy]   nvarchar(50)     NOT NULL,
    [CreateTime] datetime         NOT NULL,
    [ModifyBy]   nvarchar(50)     NULL,
    [ModifyTime] datetime         NULL,
    [Version]    int              NOT NULL,
    [Extension]  ntext            NULL,
    [AppId]      varchar(50)      NOT NULL,
    [CompNo]     varchar(50)      NOT NULL,
    [Type]       nvarchar(50)     NOT NULL,
    [ParentId]   varchar(50)      NOT NULL,
    [Code]       nvarchar(50)     NOT NULL,
    [Name]       nvarchar(50)     NOT NULL,
    [Icon]       nvarchar(50)     NULL,
    [Sort]       int              NOT NULL,
    [Enabled]    nvarchar(50)     NOT NULL,
    [Note]       ntext            NULL
);

CREATE TABLE [CmPost] (
    [Id]          varchar(50)      NOT NULL PRIMARY KEY,
    [CreateBy]    nvarchar(50)     NOT NULL,
    [CreateTime]  datetime         NOT NULL,
    [ModifyBy]    nvarchar(50)     NULL,
    [ModifyTime]  datetime         NULL,
    [Version]     int              NOT NULL,
    [Extension]   ntext            NULL,
    [AppId]       varchar(50)      NOT NULL,
    [CompNo]      varchar(50)      NOT NULL,
    [Type]        nvarchar(50)     NOT NULL,
    [UserId]      varchar(50)      NOT NULL,
    [CategoryId]  varchar(50)      NULL,
    [Title]       nvarchar(250)    NOT NULL,
    [Content]     ntext            NOT NULL,
    [Summary]     nvarchar(500)    NULL,
    [Tags]        nvarchar(200)    NULL,
    [Image]       nvarchar(250)    NULL,
    [Files]       nvarchar(250)    NULL,
    [Status]      nvarchar(50)     NOT NULL,
    [PublishTime] datetime         NULL,
    [ViewQty]     int              NULL,
    [LikeQty]     int              NULL,
    [ReplyQty]    int              NULL,
    [RankNo]      int              NULL
);

CREATE TABLE [CmReply] (
    [Id]         varchar(50)      NOT NULL PRIMARY KEY,
    [CreateBy]   nvarchar(50)     NOT NULL,
    [CreateTime] datetime         NOT NULL,
    [ModifyBy]   nvarchar(50)     NULL,
    [ModifyTime] datetime         NULL,
    [Version]    int              NOT NULL,
    [Extension]  ntext            NULL,
    [AppId]      varchar(50)      NOT NULL,
    [CompNo]     varchar(50)      NOT NULL,
    [BizType]    nvarchar(50)     NOT NULL,
    [BizId]      varchar(50)      NOT NULL,
    [UserId]     varchar(50)      NOT NULL,
    [Content]    ntext            NOT NULL,
    [ReplyTime]  datetime         NOT NULL,
    [LikeQty]    int              NULL,
    [ReplyQty]   int              NULL
);

CREATE TABLE [CmLog] (
    [Id]         varchar(50)      NOT NULL PRIMARY KEY,
    [CreateBy]   nvarchar(50)     NOT NULL,
    [CreateTime] datetime         NOT NULL,
    [ModifyBy]   nvarchar(50)     NULL,
    [ModifyTime] datetime         NULL,
    [Version]    int              NOT NULL,
    [Extension]  ntext            NULL,
    [AppId]      varchar(50)      NOT NULL,
    [CompNo]     varchar(50)      NOT NULL,
    [BizType]    nvarchar(50)     NOT NULL,
    [LogType]    nvarchar(50)     NOT NULL,
    [BizId]      varchar(50)      NOT NULL,
    [UserId]     varchar(50)      NOT NULL,
    [UserIP]     nvarchar(50)     NULL
);